name: Database Migrations on Main

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Migrate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10

      - name: Apply Database Migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: d1 migrations apply DB
          packageManager: bun
