name: Format

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
          key: format-${{ hashFiles('./bun.lock') }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install

      - name: Run Prettier
        run: bun format

      - name: Push Fixes (format your damn code, or I will do it for you and you will suffer from the resulting merge conflict)
        uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
